<?php

use Illuminate\Database\Seeder;

class MunicipalitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $municipalities = array(
            array(1, 'Ahuachapán', 1),
            array(2, 'Jujutla', 1),
            array(3, 'Atiquizaya', 1),
            array(4, 'Concepción de Ataco', 1),
            array(5, 'El Refugio', 1),
            array(6, 'Guaymango', 1),
            array(7, 'Apaneca', 1),
            array(8, 'San Francisco Menéndez', 1),
            array(9, 'San Lorenzo', 1),
            array(10, 'San Pedro Puxtla', 1),
            array(11, 'Tacuba', 1),
            array(12, 'Turín', 1),
            array(13, 'Candelaria de la Frontera', 2),
            array(14, 'Chalchuapa', 2),
            array(15, 'Coatepeque', 2),
            array(16, 'El Congo', 2),
            array(17, 'El Porvenir', 2),
            array(18, 'Masahuat', 2),
            array(19, 'Metapán', 2),
            array(20, 'San Antonio Pajonal', 2),
            array(21, 'San Sebastián Salitrillo', 2),
            array(22, 'Santa Ana', 2),
            array(23, 'Santa Rosa Guachipilín', 2),
            array(24, 'Santiago de la Frontera', 2),
            array(25, 'Texistepeque', 2),
            array(26, 'Acajutla', 3),
            array(27, 'Armenia', 3),
            array(28, 'Caluco', 3),
            array(29, 'Cuisnahuat', 3),
            array(30, 'Izalco', 3),
            array(31, 'Juayúa', 3),
            array(32, 'Nahuizalco', 3),
            array(33, 'Nahulingo', 3),
            array(34, 'Salcoatitán', 3),
            array(35, 'San Antonio del Monte', 3),
            array(36, 'San Julián', 3),
            array(37, 'Santa Catarina Masahuat', 3),
            array(38, 'Santa Isabel Ishuatán', 3),
            array(39, 'Santo Domingo de Guzmán', 3),
            array(40, 'Sonsonate', 3),
            array(41, 'Sonzacate', 3),
            array(42, 'Alegría', 11),
            array(43, 'Berlín', 11),
            array(44, 'California', 11),
            array(45, 'Concepción Batres', 11),
            array(46, 'El Triunfo', 11),
            array(47, 'Ereguayquín', 11),
            array(48, 'Estanzuelas', 11),
            array(49, 'Jiquilisco', 11),
            array(50, 'Jucuapa', 11),
            array(51, 'Jucuarán', 11),
            array(52, 'Mercedes Umaña', 11),
            array(53, 'Nueva Granada', 11),
            array(54, 'Ozatlán', 11),
            array(55, 'Puerto El Triunfo', 11),
            array(56, 'San Agustín', 11),
            array(57, 'San Buenaventura', 11),
            array(58, 'San Dionisio', 11),
            array(59, 'San Francisco Javier', 11),
            array(60, 'Santa Elena', 11),
            array(61, 'Santa María', 11),
            array(62, 'Santiago de María', 11),
            array(63, 'Tecapán', 11),
            array(64, 'Usulután', 11),
            array(65, 'Carolina', 13),
            array(66, 'Chapeltique', 13),
            array(67, 'Chinameca', 13),
            array(68, 'Chirilagua', 13),
            array(69, 'Ciudad Barrios', 13),
            array(70, 'Comacarán', 13),
            array(71, 'El Tránsito', 13),
            array(72, 'Lolotique', 13),
            array(73, 'Moncagua', 13),
            array(74, 'Nueva Guadalupe', 13),
            array(75, 'Nuevo Edén de San Juan', 13),
            array(76, 'Quelepa', 13),
            array(77, 'San Antonio del Mosco', 13),
            array(78, 'San Gerardo', 13),
            array(79, 'San Jorge', 13),
            array(80, 'San Luis de la Reina', 13),
            array(81, 'San Miguel', 13),
            array(82, 'San Rafael Oriente', 13),
            array(83, 'Sesori', 13),
            array(84, 'Uluazapa', 13),
            array(85, 'Arambala', 12),
            array(86, 'Cacaopera', 12),
            array(87, 'Chilanga', 12),
            array(88, 'Corinto', 12),
            array(89, 'Delicias de Concepción', 12),
            array(90, 'El Divisadero', 12),
            array(91, 'El Rosario array(Morazán)', 12),
            array(92, 'Gualococti', 12),
            array(93, 'Guatajiagua', 12),
            array(94, 'Joateca', 12),
            array(95, 'Jocoaitique', 12),
            array(96, 'Jocoro', 12),
            array(97, 'Lolotiquillo', 12),
            array(98, 'Meanguera', 12),
            array(99, 'Osicala', 12),
            array(100, 'Perquín', 12),
            array(101, 'San Carlos', 12),
            array(102, 'San Fernando array(Morazán)', 12),
            array(103, 'San Francisco Gotera', 12),
            array(104, 'San Isidro array(Morazán)', 12),
            array(105, 'San Simón', 12),
            array(106, 'Sensembra', 12),
            array(107, 'Sociedad', 12),
            array(108, 'Torola', 12),
            array(109, 'Yamabal', 12),
            array(110, 'Yoloaiquín', 12),
            array(111, 'La Unión', 14),
            array(112, 'San Alejo', 14),
            array(113, 'Yucuaiquín', 14),
            array(114, 'Conchagua', 14),
            array(115, 'Intipucá', 14),
            array(116, 'San José', 14),
            array(117, 'El Carmen array(La Unión)', 14),
            array(118, 'Yayantique', 14),
            array(119, 'Bolívar', 14),
            array(120, 'Meanguera del Golfo', 14),
            array(121, 'Santa Rosa de Lima', 14),
            array(122, 'Pasaquina', 14),
            array(123, 'Anamoros', 14),
            array(124, 'Nueva Esparta', 14),
            array(125, 'El Sauce', 14),
            array(126, 'Concepción de Oriente', 14),
            array(127, 'Polorós', 14),
            array(128, 'Lislique', 14),
            array(129, 'Antiguo Cuscatlán', 4),
            array(130, 'Chiltiupán', 4),
            array(131, 'Ciudad Arce', 4),
            array(132, 'Colón', 4),
            array(133, 'Comasagua', 4),
            array(134, 'Huizúcar', 4),
            array(135, 'Jayaque', 4),
            array(136, 'Jicalapa', 4),
            array(137, 'La Libertad', 4),
            array(138, 'Santa Tecla', 4),
            array(139, 'Nuevo Cuscatlán', 4),
            array(140, 'San Juan Opico', 4),
            array(141, 'Quezaltepeque', 4),
            array(142, 'Sacacoyo', 4),
            array(143, 'San José Villanueva', 4),
            array(144, 'San Matías', 4),
            array(145, 'San Pablo Tacachico', 4),
            array(146, 'Talnique', 4),
            array(147, 'Tamanique', 4),
            array(148, 'Teotepeque', 4),
            array(149, 'Tepecoyo', 4),
            array(150, 'Zaragoza', 4),
            array(151, 'Agua Caliente', 5),
            array(152, 'Arcatao', 5),
            array(153, 'Azacualpa', 5),
            array(154, 'Cancasque', 5),
            array(155, 'Chalatenango', 5),
            array(156, 'Citalá', 5),
            array(157, 'Comapala', 5),
            array(158, 'Concepción Quezaltepeque', 5),
            array(159, 'Dulce Nombre de María', 5),
            array(160, 'El Carrizal', 5),
            array(161, 'El Paraíso', 5),
            array(162, 'La Laguna', 5),
            array(163, 'La Palma', 5),
            array(164, 'La Reina', 5),
            array(165, 'Las Vueltas', 5),
            array(166, 'Nueva Concepción', 5),
            array(167, 'Nueva Trinidad', 5),
            array(168, 'Nombre de Jesús', 5),
            array(169, 'Ojos de Agua', 5),
            array(170, 'Potonico', 5),
            array(171, 'San Antonio de la Cruz', 5),
            array(172, 'San Antonio Los Ranchos', 5),
            array(173, 'San Fernando array(Chalatenango)', 5),
            array(174, 'San Francisco Lempa', 5),
            array(175, 'San Francisco Morazán', 5),
            array(176, 'San Ignacio', 5),
            array(177, 'San Isidro Labrador', 5),
            array(178, 'Las Flores', 5),
            array(179, 'San Luis del Carmen', 5),
            array(180, 'San Miguel de Mercedes', 5),
            array(181, 'San Rafael', 5),
            array(182, 'Santa Rita', 5),
            array(183, 'Tejutla', 5),
            array(184, 'Cojutepeque', 7),
            array(185, 'Candelaria', 7),
            array(186, 'El Carmen array(Cuscatlán)', 7),
            array(187, 'El Rosario array(Cuscatlán)', 7),
            array(188, 'Monte San Juan', 7),
            array(189, 'Oratorio de Concepción', 7),
            array(190, 'San Bartolomé Perulapía', 7),
            array(191, 'San Cristóbal', 7),
            array(192, 'San José Guayabal', 7),
            array(193, 'San Pedro Perulapán', 7),
            array(194, 'San Rafael Cedros', 7),
            array(195, 'San Ramón', 7),
            array(196, 'Santa Cruz Analquito', 7),
            array(197, 'Santa Cruz Michapa', 7),
            array(198, 'Suchitoto', 7),
            array(199, 'Tenancingo', 7),
            array(200, 'Aguilares', 6),
            array(201, 'Apopa', 6),
            array(202, 'Ayutuxtepeque', 6),
            array(203, 'Cuscatancingo', 6),
            array(204, 'Ciudad Delgado', 6),
            array(205, 'El Paisnal', 6),
            array(206, 'Guazapa', 6),
            array(207, 'Ilopango', 6),
            array(208, 'Mejicanos', 6),
            array(209, 'Nejapa', 6),
            array(210, 'Panchimalco', 6),
            array(211, 'Rosario de Mora', 6),
            array(212, 'San Marcos', 6),
            array(213, 'San Martín', 6),
            array(214, 'San Salvador', 6),
            array(215, 'Santiago Texacuangos', 6),
            array(216, 'Santo Tomás', 6),
            array(217, 'Soyapango', 6),
            array(218, 'Tonacatepeque', 6),
            array(219, 'Zacatecoluca', 8),
            array(220, 'Cuyultitán', 8),
            array(221, 'El Rosario array(La Paz)', 8),
            array(222, 'Jerusalén', 8),
            array(223, 'Mercedes La Ceiba', 8),
            array(224, 'Olocuilta', 8),
            array(225, 'Paraíso de Osorio', 8),
            array(226, 'San Antonio Masahuat', 8),
            array(227, 'San Emigdio', 8),
            array(228, 'San Francisco Chinameca', 8),
            array(229, 'San Pedro Masahuat', 8),
            array(230, 'San Juan Nonualco', 8),
            array(231, 'San Juan Talpa', 8),
            array(232, 'San Juan Tepezontes', 8),
            array(233, 'San Luis La Herradura', 8),
            array(234, 'San Luis Talpa', 8),
            array(235, 'San Miguel Tepezontes', 8),
            array(236, 'San Pedro Nonualco', 8),
            array(237, 'San Rafael Obrajuelo', 8),
            array(238, 'Santa María Ostuma', 8),
            array(239, 'Santiago Nonualco', 8),
            array(240, 'Tapalhuaca', 8),
            array(241, 'Cinquera', 9),
            array(242, 'Dolores', 9),
            array(243, 'Guacotecti', 9),
            array(244, 'Ilobasco', 9),
            array(245, 'Jutiapa', 9),
            array(246, 'San Isidro array(Cabañas)', 9),
            array(247, 'Sensuntepeque', 9),
            array(248, 'Tejutepeque', 9),
            array(249, 'Victoria', 9),
            array(250, 'Apastepeque', 10),
            array(251, 'Guadalupe', 10),
            array(252, 'San Cayetano Istepeque', 10),
            array(253, 'San Esteban Catarina', 10),
            array(254, 'San Ildefonso', 10),
            array(255, 'San Lorenzo', 10),
            array(256, 'San Sebastián', 10),
            array(257, 'San Vicente', 10),
            array(258, 'Santa Clara', 10),
            array(259, 'Santo Domingo', 10),
            array(260, 'Tecoluca', 10),
            array(261, 'Tepetitán', 10),
            array(262, 'Verapaz', 10)

        );

        foreach($municipalities as $municipality) {
            $array = array_values($municipality);
            DB::table('municipalities')->insert([
                'id' => $array[0],
                'name' => $array[1],
                'department_id' => $array[2]
            ]);
        }
    }
}
